export const CHANGE_DAILY_CURRENTDATE = "CHANGE_DAILY_CURRENTDATE";
export const CHANGE_WEEKLY_CURRENTDATE = "CHANGE_WEEKLY_CURRENTDATE";
export const CHANGE_MONTHLY_CURRENTDATE = "CHANGE_MONTHLY_CURRENTDATE";
